apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Environment
metadata:
  name: my-env
spec:
  path: ./path/to/env
  source:
    url: https://gitprovider.com/org/repo
    ref:
      branch: main
  dependentObjects:
    workloadRef:
    - kind: Deployment
      name: my-deployment
