apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Environment
metadata:
  name: prod-2
  namespace: default
spec:
  path: ./envs/prod-2
  source:
    url: https://github.com/thomasstxyz/mtpoc-infra-3
    ref:
      branch: main
    secretRef:
      name: mtpoc-infra-3-ssh
  apiTokenSecretRef:
    name: github-api-token
  gitProvider: github