apiVersion: promotions.gitopsprom.io/v1alpha1
kind: Environment
metadata:
  name: prod-1
  namespace: default
spec:
  path: ./envs/prod-1
  source:
    url: https://github.com/thomasstxyz/mtpoc-infra-2
    ref:
      branch: main
    secretRef:
      name: mtpoc-infra-2-ssh
  apiTokenSecretRef:
    name: github-api-token
  gitProvider: github